### ISSUE TITLE
Proper submodule commands need to be added for setup

### ISSUE THREAD

**Issue by RyPeck** [OpenSOC/opensoc-ui#14]
The [Setup development environment](https://github.com/OpenSOC/opensoc-ui#setup-development-environment) and deployment instructions don't include instructions for initializing and updating the submodules (kibana).

I believe all that needs to be run is - 

    git submodule update --init --recursive

Or you could instruct users to clone the repo using the command - 

    git clone --recursive

**Comment by rammie** [comment]
Done. The README.md has been updated.
